name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
      with:
        persist-credentials: false
    - uses: actions/setup-python@v5.3.0
      with:
        python-version: '3.14'
          # cache: 'pipenv' # caching pipenv dependencies
    - name: Install poetry and pipx
      run: |
        pip install uv && pip install pipx
    - name: Install global dependencies
      run: |
        pipx install uv
    - name: Run Makefile
      run: make check
    - name: Run make
      run: uv run hatch build
